### ISSUE TITLE
New icon for application-x-deb

### ISSUE THREAD

**Issue by darealshinji** [linuxmint/mint-x-icons#102]
I was thinking about a new icon for Debian packages, a combination of the archive symbol (since .deb files are "packages" and technically archives) and the Mint logo. But I also made some drafts involving the Debian logo.

![deb](https://cloud.githubusercontent.com/assets/5700937/7440551/028d7bd8-f0bd-11e4-951f-ed4c607d2ac5.png)

What do you think?

**Comment by JosephMcc** [comment]
The icon theme already has some of these which could be re-used. In apps check out softwarecenter-debain.png for example. If you were going to go with this style I would stick with ones that keep the logo in the same place and in the same style as the existing ones.

**Comment by darealshinji** [comment]
I personally like icon 4. Here's the source code of it: https://gist.github.com/darealshinji/a8ffffe77a03badd0c86
I've added the Debian logo from softwarecenter-debain.svg to the gray gears background but I don't think it looked good.
But if you prefer archive symbols for .deb files re-using the softwarecenter-debain icon is probably a good idea.

**Comment by GLolol** [comment]
I feel like 4 and the current one are the best choices. For the first 3, the icons seem a bit awkwardly placed: in 1, the mint logo slightly covers the tape of the package icon, and in the others the Debian logo doesn't contrast well enough with the package background. Having a flat logo overlap a 3D-looking object looks bad IMO.
