### ISSUE TITLE
Source SVGs for smaller icon size

### ISSUE THREAD

**Issue by johnbeard** [linuxmint/mint-x-icons#141]
When creating icons, I would like to be able to reuse elements from other icons (especially things like the borders, shadows and highlights). However, especially for the app icons, SVG sources are only there for the 96px sizes. A naive rescale down to 16/22/24/48, etc. often doesn't look good - you need to do it carefully, by reducing detail, increasing contrasts and aligning pixels to avoid anti-aliasing ruining the image.

I understand that the < 96px sizes are PNG images for software compatibility, but would it be possible to maintain a separate "source" directory in this repo, so we can share the SVG sources for smaller icons. It's also much much easier to modify an icon if you have access to the SVG source than having to use a pixel editor on the flattened image or recreate the SVG yourself.

Perhaps a folder in the top level of the repo called `src/Mint-X[-colour]/apps/[XX]px` which can contain SVGs?

If this folder were created, people contributing smaller SVGs that they used to create the PNGs already committed would make it much easier to create a new icon in this theme.

**Comment by JosephMcc** [comment]
I personally wouldn't be against the idea of doing something like this. It would produce better images at small sizes but creating the images for all the existing icons would be a massive undertaking. It would mostly be for anything new that was added.

**Comment by johnbeard** [comment]
Sure, I wouldn't expect SVGs to be created when the icon exists, unless there are some SVGs sources that creators already had around - if there are any, this would be a huge help in making new icons as the borders and gradients can be copied for a consistent look.

**Comment by JosephMcc** [comment]
Mint-X is based on the Faenza icon theme. The original sources are floating around on the internet which contained some template svgs you could use. A search should find them.

**Comment by JosephMcc** [comment]
We now have a src/ directory for any new icons. I added the original base faenza icons to make creation of new icons a bit easier.
