### ISSUE TITLE
[Feature Request] Custom Folder Emblems

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-x-icons#149]
It would be great to be able to set custom icons as folder emblems. For example I want to be able to set the GitHub Logo as emblem on some of my folders.

**Comment by JosephMcc** [comment]
Not clear what you're after here. Do you want to be able to set an icon of your choice as an emblem or do you want to see more emblems supported in Mint-X? The first really isn't an issue with Mint-X. The second would be. If it's the second feel free to suggest some you would like to see.

**Comment by NikoKrause** [comment]
@JosephMcc
I want the first one.

**Comment by JosephMcc** [comment]
Well that's more an issue for nemo-extensions: https://github.com/linuxmint/nemo-extensions or for the caja implementation which I don't happen to know the link for.
