### ISSUE TITLE
Icon for FCEUX (hardcoded)

### ISSUE THREAD

**Issue by sergioad** [linuxmint/mint-x-icons#152]
Hello friends why do you not add a Faenza icon for FCEUX? having the ZSNES icon will not be too hard, the only thing you need to do is removing two of the four buttons, resize the two remaining to a little bit bigger size and them change the colors of them to red, label them as A and B and that is it

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
