### ISSUE TITLE
Icon for VBA-M and mGBA

### ISSUE THREAD

**Issue by sergioad** [linuxmint/mint-x-icons#153]
Hello friends, could you create an icon for both VBA-M and mGBA? again, having the ZSNES icon you only need to make the background purple, remove the X and Y buttons, resize the A and B buttons and change the color of the D-Pad and buttons to light grey like in the original GBA, the icon names are mgba and vbam

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
