### ISSUE TITLE
Icon for GNOME Twitch

### ISSUE THREAD

**Issue by sergioad** [linuxmint/mint-x-icons#154]
Hello friends could you do an icon for GNOME Twitch? GNOME Twitch is a GNOME app made for the GNOME desktop to let the users stream their favorite Twitch content with not flash nor a browser

Icon= gnome-twitch
Page with the full description and icon=https://wiki.gnome.org/Apps/GnomeTwitch

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
