### ISSUE TITLE
Icon for Gens / Gens GS (hardcoded)

### ISSUE THREAD

**Issue by sergioad** [linuxmint/mint-x-icons#155]
Hello friends, could you add an icon for Gens and Gens GS? I love the emulators but sincerelly both of them uses an ugly icon, maybe you could made a black icon with the SEGA Genesis logo or maybe with the word Gens inside of it, what do you think?

Icon=gensgs

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
