### ISSUE TITLE
Icon for Mumble

### ISSUE THREAD

**Issue by sergioad** [linuxmint/mint-x-icons#156]
Hello friends could you make an icon for Mumble? as you may know Mumble is an Opensource low latency voice chat client wich is mainly used by gamers for live chat but also now it is used by some podcasters as an opensource and lightweight replacement for skype wich allows them to record the chat, could be amazing to have a proper icon for it :smile: 

IconName=mumble
Icon=https://en.wikipedia.org/wiki/Mumble_(software)

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
