### ISSUE TITLE
Icon for GNOME 2048

### ISSUE THREAD

**Issue by sergioad** [linuxmint/mint-x-icons#157]
Hello friends, could you make an icon for GNOME 2048? this app is a really adictive puzzle game released as part of the GNOME games, the icon coul be a blue icon with a white 2048 text

IconName=gnome-2048

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
