### ISSUE TITLE
Linux kernel icon looks like icon of a closed-source competitor

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mint-x-icons#162]
In Nemo, the icon of `/vmlinuz` looks like the logo of a well-known closed-source competitor.  

The icon seems to be `/usr/share/icons/Mint-X/mimetypes/32/application-x-ms-dos-executable.png`

Until a MIME-types database (such as `/usr/share/mime/packages/freedesktop.org.xml`) is possibly fixed upstream to detect the Linux kernel specially, can the `application-x-ms-dos-executable.png` icon be changed, maybe to something like
`/usr/share/icons/gnome/32x32/mimetypes/application-x-executable.png`?  
![application-x-executable](https://cloud.githubusercontent.com/assets/11039718/23191042/91c844a8-f869-11e6-9170-3301a71246bb.png)

APT `mint-x-icons` package version 1.4.0

**Comment by xenopeek** [comment]
Not here. I suspect you installed something (like Wine) that changes default mime type icons.
