### ISSUE TITLE
Mint-X-Dark sound icon blurry in Xfce

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-x-icons#166]
![bildschirmfoto_2017-07-05_13-49-16](https://user-images.githubusercontent.com/8415124/27863094-ce86bb3a-6188-11e7-9751-77993d37b5f8.png)

**Comment by smkent** [comment]
#170 will likely fix this.

**Comment by NikoKrause** [comment]
@smkent Thanks
