### ISSUE TITLE
Icons for Virtaal app and TMX files

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/mint-x-icons#167]
In the absence of Mint icons for these, I've created symlinks **poedit.png** > **virtaal.png**  and **text-xhtml+xml.png** > **x-translation.png**

**Comment by xenopeek** [comment]
Thanks for contributing to nemo-x-icons. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
