### ISSUE TITLE
Missing icons for Cairo-Dock

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/mint-x-icons#168]
There's only 96px icon for cairo-dock app - other sizes are missing - e.g. resulting in an outgrown icon in system monitor.
Maybe including Mint-Y in the Inherits line can suffice?

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mint-x-icons/commit/4d9aab6bdce1d6ad06d3122e874d3bab14e49dcc
