### ISSUE TITLE
The Mint-X-Dark icon theme is missing the VPN lock icon wifi panel indicator

### ISSUE THREAD

**Issue by bobbysaget** [linuxmint/mint-x-icons#174]
Mint 18.3 Xfce

The mint-x-dark icon theme (white icon set included for use with mint Xfce dark themes such as mint-y and mint-x-dark) is missing the padlock-style VPN indicator over the wifi icon showing users at-a-glance whether they are connected to VPN. Just as is the case with the default icon set, there should also be two separate icons in this set, for use depending on whether you are connected to a VPN. Currently, both VPN and non-VPN connections display the same wifi icon.

I created a [forum thread](https://forums.linuxmint.com/viewtopic.php?f=211&t=252011) for this issue in August, which includes pictures of what I'm talking about for reference, and then Clem recently told me on the blog this was the place to post my issue.

**Comment by rwpreece** [comment]
The mint-x only has 16x16 svg files in "scalable", so not very scalable.  That's the only place I could find any semblance of them at all.  Irritating.

**Comment by rwpreece** [comment]
Actually, it displays in my LMDE2 and it only has these two scalable fonts I mentioned about.  Maybe it's related to the network@cinnamon.org applet.  It does have differences between the version in LMDE 2 Betsy and 18.3.

**Comment by JosephMcc** [comment]
The Mint-X-Dark icon theme had never been very complete. The plan is to switch to Mint-Y in Mint19 and take a different approach with many of these icons and avoid the need for a separate dark version of the theme.
