### ISSUE TITLE
Mint X icons no longer appear on theme options in Arch Linux

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/mint-x-icons#188]
**Issue**
Mint X icons no longer appear on the theme options within Cinnamon, I have received some reports on the icon set no longer available despite having installed the icon theme properly and the folders on /usr/share/icons. This happens on Arch Linux and derivatives

Maybe an update of GNOME or GTK did something and this break the ability to find the icon theme, however I haven't been able to test if so and which one was it (in case it applies)

**Steps to reproduce**
Install package "mint-x-icons" from AUR

**Expected behaviour**
Mint-X and any of its variants should appear on theme options

**Actual behaviour**
Mint-X and any of its variants doesn't appear on theme options, despite having the icons properly set

**Other information**
Information on the issue as well as xsession-errors file attached

![Mint X missing 1](https://user-images.githubusercontent.com/1509924/65050139-2687e100-d924-11e9-88d2-b5a5a2ee4c36.png)

![Mint X missing 2](https://user-images.githubusercontent.com/1509924/65050141-27207780-d924-11e9-87a5-3f6b940aae56.png)

[xsession-errors.tar.gz](https://github.com/linuxmint/mint-x-icons/files/3621832/xsession-errors.tar.gz)

**Comment by Boolicious** [comment]
It still shows up in the GTK inspector's "Icon Theme" option.
Selecting Mint-X (or any of it's variants) does make the app use the icons

Not sure if related but this appears either immediately after I switch to Mint-X in the inspector or when certain icons get displayed
![image](https://user-images.githubusercontent.com/49502778/65142127-968d8880-da44-11e9-83ef-2b1259c76926.png)

**Comment by JosephMcc** [comment]
Do you get any errors or anything if you run `cinnamon-settings themes` from a terminal?

**Comment by Boolicious** [comment]
> Do you get any errors or anything if you run `cinnamon-settings themes` from a terminal?

```
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Aqua/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Aqua/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Blue/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Blue/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Brown/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Brown/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Grey/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Grey/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Orange/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Orange/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Pink/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Pink/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Purple/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Purple/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Red/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Red/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Sand/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Sand/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Teal/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Teal/places/48/folder.svg
Caught GLib.Error exception: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/boolicious/.icons/Mint-X-Yellow/places/48/folder.svg” (3)
path: /home/boolicious/.icons/Mint-X-Yellow/places/48/folder.svg
```

**Comment by jlvermeulen** [comment]
Just want to say I encounter the same problem, with the same errors, on Fedora.

**Comment by SamBurgos** [comment]
My apologies for not answering previously but real life work has been hard lately, after checking the comments on the package (I am the packager of mint-x-icons on Arch) it seems that this is/was caused by an upgrade of another package (shared-mime-info), I [already tested the solution given here](https://aur.archlinux.org/packages/mint-x-icons/#comment-708375) and it works for now, but I am not really sure what changed between those versions that broke the icon theming

I am not sure which version uses Ubuntu, Linux Mint, Fedora or any other distros, but this might give you something to work with and maybe perform additional tests @JosephMcc, other than that I am out of options or extra testing for now

**Comment by yparitcher** [comment]
upstream issue https://gitlab.freedesktop.org/xdg/shared-mime-info/issues/116 
fixed in shared-mime-info 1.14 
tested in archlinux

**Comment by JosephMcc** [comment]
So it looks like this was broken and fixed by something else :) It seems it wasn't limited to just Mint-X. I'm going to go ahead and close this since the issue was found. Maybe at some point I'll figure out why it only affected Mint-X and not Y in the first place.

**Comment by SamBurgos** [comment]
@JosephMcc yes, it was indeed shared-mime-info package, in Arch Linux upgrading to version 1.14 fixes the issue as @yparitcher stated, you might wanna check if in the case of Ubuntu/Linux Mint (or Fedora in the case of @jlvermeulen ) happens the same with versions 1.12 and 1.14 (that fixes or prevent the issue from happening) and version 1.13 (which contains the problem) and which of these versions might be available in those distros

As for something to test, after barely checking the commits on that package, it seems that somehow it broke compatibility with several svg files and they try to fix it back in several stages, perhaps you can check the commits there when possible
