### ISSUE TITLE
Where is GIMP's Wilber?

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/mint-x-icons#77]
The logo of GIMP is an animal head with the name Wilber. However, in the Mint-X icons it's replaced by an (in my opinion) ugly painting palette.  
Would it be possible to change this? I've changed it manually by editing the desktop file, but I think lots of people would find GIMP better in the menu when its logo was used.

![gimp](https://cloud.githubusercontent.com/assets/5564491/5320300/fba484a4-7cb0-11e4-9a71-25b105560b3e.png)  ![gimp-wilber](https://cloud.githubusercontent.com/assets/5564491/5320305/0136cfb2-7cb1-11e4-97b9-9de1f2c82674.png)

**Comment by clefebvre** [comment]
It might look better without the colors underneath. Can you make a PR?

**Comment by theSeppi** [comment]
Do you mean Wilber on the woody background or simply Wilber without anything behind it?
Another question: Is it enough to put an SVG in all the 96...16 folders or do I have to export PNG's for the

**Comment by JosephMcc** [comment]
Probably Wilber on the woody background. Just remove the paint splotches from the background first. For file types probably stick with  the existing convention, SVG at 96 and export PNG for the others.

**Comment by theSeppi** [comment]
#89

**Comment by darealshinji** [comment]
I guess this can be closed now since the PR was merged (https://github.com/linuxmint/mint-x-icons/commit/b5af9f2122197b8eb9b1f9ea55cdc3c3ef8ca9f5).
