### ISSUE TITLE
Steam tray icon

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mint-x-icons#91]
Default steam tray icon is light and invisilbe with light themes. I suggest "sudo cp /usr/share/icons/Mint-X/apps/48/steam.png /usr/share/icons/Mint-X/apps/48/steam_tray_mono.png" And steam tray icon will be Faenza-like and visible with all themes

**Comment by JosephMcc** [comment]
Did you try this and did it work? I don't actually use steam but if that solution works I can make a PR to add the steam_tray_mono icons to the theme. Just need to be sure the naming is correct so it works as expected.

**Comment by Yanpas** [comment]
Yes, I have tried it and it works. I ran "sudo update-icon-caches /usr/share/icons/Mint-X" after it.
BTW I don't know if Mint icons in repo are SVG or PNG

**Comment by JosephMcc** [comment]
Ok. I'll make a PR to add it. The icons are a combination of svg and png depending on the size.

**Comment by GLolol** [comment]
A simple symlink looks like it might work for this.

**Comment by darealshinji** [comment]
![steam_tray_mono](https://cloud.githubusercontent.com/assets/5700937/7341232/1e91c5be-ec9e-11e4-8939-f09ec8d5eb76.png)
I think it would be better to use this for the tray instead, which is a color-inverted version of ~/.steam/public/steam_tray_mono.png.

**Comment by clefebvre** [comment]
I agree with @darealshinji except that the icon shouldn't just be made of black + transparent, but black + light grey, ideally with a light grey contour around the dark part.

**Comment by darealshinji** [comment]
Maybe you can create something from this SVG version: http://boneyardbrew.deviantart.com/art/Modern-Steam-Icon-421263397
