### ISSUE TITLE
Thunar doesn't recognize ODP

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mint-x-icons#95]
On the screenshot Nautilus on the left and thunar on the right. Maybe these icons are gtk3 only? I'm not sure if this bug thunar's or mint-X's
![bug](https://cloud.githubusercontent.com/assets/7345761/7400491/f6e3cf92-eec5-11e4-8eaf-066fed1663e2.png)

**Comment by Yanpas** [comment]
Problematic: otp, ots, ott, odp

**Comment by JosephMcc** [comment]
This seems to be fine in nautilus, nemo and caja so my assumption would be the problem lies with Thunar.

**Comment by Yanpas** [comment]
The same is in pcmfanfm. But Thunar is Mint supported file manager. Guess some extra icon links should be created. I was trying to investigate which, but no results.

**Comment by Yanpas** [comment]
I've found the reason of issue, wait for PR

**Comment by Yanpas** [comment]
Theme needs separate icons for templates, so `ot?` is new bug now. New icons should be applied to all FM. See #127. ODP is fixed by my commit
