### ISSUE TITLE
Port some Libreoffice icons from Sifr theme

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mint-x-icons#96]
Mint LO icon theme (named Humanity) has lack of icons and new 4.4 version has a lot of titles instead of icons. And older versions has lack of icons too. Sifr is very similar to Mint theme, so porting drawing panel and some other icons won't be eclectically. I may add some screenshots and name missing icons if devs are using older LO versions

**Comment by JosephMcc** [comment]
It would prove a big help if you gave more details on what exactly it's missing. I don't use LO really and the version I have is 4.3.

**Comment by Yanpas** [comment]
![screenshot - 05192015 - 06 02 03 pm](https://cloud.githubusercontent.com/assets/7345761/7706270/21240cf4-fe52-11e4-9066-b909189f04c6.png)
![screenshot - 05192015 - 06 02 15 pm](https://cloud.githubusercontent.com/assets/7345761/7706268/20ffbf70-fe52-11e4-9e80-80f252d47662.png)
![screenshot - 05192015 - 06 02 29 pm](https://cloud.githubusercontent.com/assets/7345761/7706267/20ffb818-fe52-11e4-9a47-5acc1e869df1.png)
![screenshot - 05192015 - 06 02 44 pm](https://cloud.githubusercontent.com/assets/7345761/7706269/21033bbe-fe52-11e4-9d77-810b2b1ebdc2.png)
Buttons without icons are on the screenshots (1st and 2nd panels for Draw, Impress, Cals and Writer). Moreover next moth is coming Libreoffice 5.0 with remade panels for Draw and Impress
https://wiki.documentfoundation.org/ReleaseNotes/5.0#General_UI_changes
What was added to Impress:
* zoom and pan (scope with + - on it)
* Slide layout (or bckgranound)
* start from current slide
* Remove slide (?)

to Draw:
* Export
other buttons are mixed
